# Generated by Django 3.1.2 on 2021-10-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='club',
        ),
    ]
